#!/usr/local/bin/python3

import requests

url = 'https://api.openweathermap.org/data/2.5/weather?q=grand%20rapids&appid=put_key_here'
r = requests.get(url)
data = r.json()
temp = data['main']['temp'] - 273.13
temp = round(temp * 9 / 5 + 32, 1)
print(temp)
